### ISSUE TITLE
NPM deprecation warnings when running `sf run function start`

### ISSUE THREAD

**Issue by edmorley** [forcedotcom/sf-fx-runtime-nodejs#383]
If I use `sf generate function -l typescript -n foo` to generate a template TypeScript function, then run the function using `sf run function start` (with Node.js v18.7.0 installed locally), I get a bunch of deprecation warnings:

```
$ sf run function start
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

Ideally there would be no deprecation warnings shown.

cc @joshwlewis @colincasey

**Comment by joshwlewis** [comment]
These are all fixed by https://github.com/heroku/sf-functions-core/pull/55 (which includes function template updates including a Node.js bump and dependency bumps).
